name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: contains(join(github.event.commits.*.message, ' '), 'fix') || contains(join(github.event.commits.*.message, ' '), 'feat') || contains(join(github.event.commits.*.message, ' '), 'BREAKING CHANGE')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make script executable
        run: chmod +x ./quickbuild.sh

      - name: Build with Maven
        run: ./quickbuild.sh

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - name: Create a GitHub release
        if: steps.tag_version.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
